### PR TITLE
fix: cannot find module jiti when stub import fails

### LINKED ISSUE #588: Weird issues after upgrading to version 1.0
Hi

After upgrading to version 1.0.0 and following the guide - we have started to see this error in a project that uses a shared component

```
[ nuxi  12:01:24 PM]  ERROR  Cannot start nuxt:  Error while importing module @gyldendalsolutions/sharedcomponents: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Volumes/dev/repos/my_ibooks_frontend/node_modules/.pnpm/jiti@2.4.2/node_modules/jiti/node_modules/.pnpm/jiti@2.4.2/node_modules/jiti/lib/jiti.mjs' imported from /Volumes/dev/repos/my_ibooks_frontend/node_modules/.pnpm/jiti@2.4.2/node_modules/jiti/lib/jiti.mjs
    at loadNuxtModuleInstance (node_modules/.pnpm/@nuxt+kit@3.16.2_magicast@0.3.5/node_modules/@nuxt/kit/dist/index.mjs:2565:15)
    at async installModule (node_modules/.pnpm/@nuxt+kit@3.16.2_magicast@0.3.5/node_modules/@nuxt/kit/dist/index.mjs:2480:67)
    at async initNuxt (node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_@types+node@22.14.0_db0@0.3.1_eslint@9.24.0_jiti@2.4._0bcfd39a16c7773726dbc85ef80643ae/node_modules/nuxt/dist/shared/nuxt.iYoBCR2R.mjs:5833:5)
    at async NuxtDevServer._load (node_modules/.pnpm/@nuxt+cli@3.24.1_magicast@0.3.5/node_modules/@nuxt/cli/dist/chunks/dev2.mjs:183:5)
    at async NuxtDevServer.load (node_modules/.pnpm/@nuxt+cli@3.24.1_magicast@0.3.5/node_modules/@nuxt/cli/dist/chunks/dev2.mjs:111:7)
    at async NuxtDevServer.init (node_modules/.pnpm/@nuxt+cli@3.24.1_magicast@0.3.5/node_modules/@nuxt/cli/dist/chunks/dev2.mjs:106:5)
    at async Object.run (node_modules/.pnpm/@nuxt+cli@3.24.1_magicast@0.3.5/node_modules/@nuxt/cli/dist/chunks/dev-child.mjs:95:5)
    at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:316:16)
    at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:307:11)
    at async runMain (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:445:7)
```

```
The componets works fine with 0.8.4 - but is included via
 "@gyldendalsolutions/sharedcomponents": "file:../sharedcomponents",
```

Could that cause an issue with the latest version?

### LINKED ISSUE #642: Cannot find module jiti
I updated quite a few dependency of my module and since then I run into an error when I execute `yarn dev:prepare`.

I already deleted `dist`, `node_modules` and have a fresh install with node 22 but the error is the same.

```bash
yarn dev:prepare  
yarn run v1.22.22
$ nuxt-module-build build --stub && nuxt-module-build prepare && nuxi prepare playground
ℹ Stubbing nuxt-api-shield                                                                                                                                  10:08:18
ℹ Cleaning dist directory: ./dist                                                                                                                           10:08:18

[10:08:18]  ERROR  Cannot find module '/home/rrd/public_html/nuxt-api-shield/node_modules/jiti/node_modules/jiti/lib/jiti.mjs' imported from /home/rrd/public_html/nuxt-api-shield/node_modules/jiti/lib/jiti.mjs

    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:685:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:634:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:617:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:273:38)
    at onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:577:36)
    at TracingChannel.tracePromise (node:diagnostics_channel:344:14)
    at ModuleLoader.import (node:internal/modules/esm/loader:576:21)
    at defaultImportModuleDynamicallyForModule (node:internal/modules/esm/utils:215:31)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:254:12)
    at Object.nativeImport (node_modules/jiti/lib/jiti.mjs:9:30)
    at nativeImportOrRequire (node_modules/jiti/dist/jiti.cjs:1:190382)
    at jitiRequire (node_modules/jiti/dist/jiti.cjs:1:189876)
    at import (node_modules/jiti/dist/jiti.cjs:1:199778)
    at dist/module.mjs:1:215
    at eval_evalModule (node_modules/jiti/dist/jiti.cjs:1:196325)
    at node_modules/jiti/dist/jiti.cjs:1:194552
    at async Function.import (node_modules/jiti/dist/jiti.cjs:1:199772)
    at async rollup:done (node_modules/@nuxt/module-builder/dist/chunks/build.mjs:143:28)
    at async rollupBuild (node_modules/unbuild/dist/shared/unbuild.BQ_Ce1-K.mjs:869:5)
    at async _build (node_modules/unbuild/dist/shared/unbuild.BQ_Ce1-K.mjs:1318:7)
    at async build (node_modules/unbuild/dist/shared/unbuild.BQ_Ce1-K.mjs:1138:5)
    at async Object.run (node_modules/@nuxt/module-builder/dist/chunks/build.mjs:46:5)
    at async runCommand (node_modules/citty/dist/index.mjs:316:16)
    at async runCommand (node_modules/citty/dist/index.mjs:307:11)
    at async runMain (node_modules/citty/dist/index.mjs:445:7)
```

I have tried to find out what causes this, but I have no clue how to go forward.

```bash
find node_modules -name "jiti" -type d   
node_modules/.cache/jiti
node_modules/jiti
node_modules/mkdist/node_modules/jiti
```

The repo is https://github.com/rrd108/nuxt-api-shield, I did not managed to create a more minimal reproduction.

### PR DESCRIPTION
**Pull request by BobbieGoede**
### 🔗 Linked issue
* #642 
* #588

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Resolves #642
Resolves #588

I'm sure there is a better way to solve this issue. 

I narrowed down the issue here https://github.com/nuxt/module-builder/issues/588#issuecomment-3072810778, basically if an error is thrown while importing the module natively, jiti will attempt to import it again, in this attempt it will error due to the relative import to jiti not resolving correctly which in turn hides the original error that was thrown.

Using jiti's `tryNative` option also seems to resolve this issue, but I'm not sure if it has other implications.

### CODE REVIEW

**Comment by BobbieGoede** [comment]
Here's a reproduction, simply throw an error and see the error is obfuscated by the jiti import error https://stackblitz.com/edit/github-dzqjja7l?file=src%2Fmodule.ts

image


And here's the same reproduction using the preview release of this PR https://stackblitz.com/edit/github-dzqjja7l-mqatxhwe?file=src%2Fmodule.ts

image

**Comment by danielroe** [comment]
i think this might need to be implemented in unbuild - i've gotten the same issue in the nuxt core repo which doesn't use the module builder

**Comment by BobbieGoede** [comment]
@danielroe 
I tried reproducing the issue using unbuild only, the main issue is that we have an additional step that imports the stub with jiti. 

Reproduction: https://stackblitz.com/edit/github-haxspghd?file=build.config.mjs

Maybe a cleaner solution would be to only use jiti if the build is not a stub?

**Comment by BobbieGoede** [comment]
@danielroe 
I have opened https://github.com/unjs/unbuild/pull/542 which should resolve this issue from unbuild.
