### ISSUE TITLE
Weird issues after upgrading to version 1.0

### ISSUE THREAD

**Issue by thomashohn** [nuxt/module-builder#588]
Hi

After upgrading to version 1.0.0 and following the guide - we have started to see this error in a project that uses a shared component

```
[ nuxi  12:01:24 PM]  ERROR  Cannot start nuxt:  Error while importing module @gyldendalsolutions/sharedcomponents: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Volumes/dev/repos/my_ibooks_frontend/node_modules/.pnpm/jiti@2.4.2/node_modules/jiti/node_modules/.pnpm/jiti@2.4.2/node_modules/jiti/lib/jiti.mjs' imported from /Volumes/dev/repos/my_ibooks_frontend/node_modules/.pnpm/jiti@2.4.2/node_modules/jiti/lib/jiti.mjs
    at loadNuxtModuleInstance (node_modules/.pnpm/@nuxt+kit@3.16.2_magicast@0.3.5/node_modules/@nuxt/kit/dist/index.mjs:2565:15)
    at async installModule (node_modules/.pnpm/@nuxt+kit@3.16.2_magicast@0.3.5/node_modules/@nuxt/kit/dist/index.mjs:2480:67)
    at async initNuxt (node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_@types+node@22.14.0_db0@0.3.1_eslint@9.24.0_jiti@2.4._0bcfd39a16c7773726dbc85ef80643ae/node_modules/nuxt/dist/shared/nuxt.iYoBCR2R.mjs:5833:5)
    at async NuxtDevServer._load (node_modules/.pnpm/@nuxt+cli@3.24.1_magicast@0.3.5/node_modules/@nuxt/cli/dist/chunks/dev2.mjs:183:5)
    at async NuxtDevServer.load (node_modules/.pnpm/@nuxt+cli@3.24.1_magicast@0.3.5/node_modules/@nuxt/cli/dist/chunks/dev2.mjs:111:7)
    at async NuxtDevServer.init (node_modules/.pnpm/@nuxt+cli@3.24.1_magicast@0.3.5/node_modules/@nuxt/cli/dist/chunks/dev2.mjs:106:5)
    at async Object.run (node_modules/.pnpm/@nuxt+cli@3.24.1_magicast@0.3.5/node_modules/@nuxt/cli/dist/chunks/dev-child.mjs:95:5)
    at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:316:16)
    at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:307:11)
    at async runMain (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:445:7)
```

```
The componets works fine with 0.8.4 - but is included via
 "@gyldendalsolutions/sharedcomponents": "file:../sharedcomponents",
```

Could that cause an issue with the latest version?

**Comment by vitebo** [comment]
I've been able to **consistently reproduce this issue** in a Nuxt project using `nuxt-module-build`.

In my case, the error:

```
Cannot find module '.../node_modules/.pnpm/jiti@2.4.2/node_modules/.pnpm/jiti@2.4.2/node_modules/jiti/lib/jiti.mjs'
```

only occurs when the Nuxt module being imported by `nuxt-module-build` depends on code that uses browser-specific APIs at the top level. A concrete example is using the `session-storage` driver from `unstorage`.

When I change the implementation to something like this:

```ts
import { createStorage } from 'unstorage'
// import sessionStorageDriver from 'unstorage/drivers/session-storage'
import memoryDriver from 'unstorage/drivers/memory'

export const storage = createStorage({
  // driver: sessionStorageDriver({ base: 'my-lib' }),
  driver: memoryDriver(),
})
```

then `nuxt-module-build build --stub` works as expected.

---

### Observed behavior

During `build --stub`, `nuxt-module-build` loads the Nuxt module using `jiti(cwd)(...)`, which executes the `module.mjs` file directly in a Node.js context. If that file (or any transitive import) accesses `window`, `sessionStorage`, or other browser-only APIs, it fails at runtime — and the result is a misleading module resolution error, even though the issue is with execution.

---

### My question

Is this something `nuxt-module-build` intends to handle more gracefully in the future?
Or is this a case where module authors should avoid referencing browser-only logic at the top level (especially when using `--stub`)?

To help with debugging, I’ve created a minimal reproduction here:
👉 https://github.com/vitebo/nuxt-module-build-issue-588-repro

**Comment by thomashohn** [comment]
Any news her @danielroe ?

**Comment by BobbieGoede** [comment]
This issue is not related to browser-specific API usage, the ambiguous error is thrown whenever an error is thrown while the module code is imported/ran during build/stub.

To reproduce the following should be enough:

```ts
import { defineNuxtModule } from '@nuxt/kit'

export default defineNuxtModule({
  setup(_options, _nuxt) {},
})

throw new Error(
  'This error will be hidden, a `Cannot find module` with a path to jiti will be printed instead.'
  + 'Followed by a second error `Cannot load module. Please check dist: (path)/dist/module.mjs`',
)
```

Reproduction projects here as well https://github.com/nuxt/module-builder/pull/644#issuecomment-3106601962
