### ISSUE TITLE
Module build error when importing runtime code outside the runtime directory 

### ISSUE THREAD

**Issue by cjpearson** [nuxt/module-builder#375]
We first noticed this issue when updating from 0.6.0 to 0.7.1. 

If you are importing a function from the runtime directory into `module.ts`, it will fail if the full path to the file includes a period in the path. For example, in my case: `/Users/connor.pearson/projects/my-module` The directory with the period is parsed as the file instead of the actual file.

Sample reproduction: https://github.com/cjpearson/nuxt-module-builder-filename-issue

To run: `yarn && yarn dev:prepare && yarn nuxt-module-build build`

```
ERROR  Cannot find module /Users/connor.pearson/Downloads/filename-test/dist/runtime/utils/connor imported from file:///Users/connor.pearson/Downloads/filename-test, file:///Users/connor.pearson/Downloads/, file:///Users/connor.pearson/Downloads/filename-test/_index.js, file:///Users/connor.pearson/Downloads/node_modules
```

The project directory or one of its ancestors should include a "." in the path.

I've added an upstream issue [here](https://github.com/unjs/pathe/issues/184), but maybe this could be fixed by using `basename` [here](https://github.com/nuxt/module-builder/blob/main/src/commands/build.ts#L122) instead?

**Comment by danielroe** [comment]
This has been fixed in the latest `pathe`, which will be included in the next release.

**Comment by sandros94** [comment]
Facing this issue with a `import { Stuff } from './runtime/types'` inside my `module.ts`. Forcing `pathe@2.0.1` doesn't seem to solve it.

- Detailed [error in CI](https://github.com/sandros94/lab/actions/runs/12737157265/job/35497907331)
- Line that [causes the issue](https://github.com/sandros94/lab/blob/e8d13b146463fb68e6f7cfaf2cdd48383f3832a2/src/module.ts#L16-L20)

For now I'm going to duplicate types, but I would like to understand what causes it, is it really just the period in `types/index.d`?

Edit: just noticed that this isn't an issue on a windows fs 🤔

**Comment by danielroe** [comment]
@sandros94 Typically you should not author `.d.ts` files. And if you do you should not import from them. Instead, author `.ts` files, and the `.d.ts` files are produced _from_ them.

**Comment by sandros94** [comment]
> [@sandros94](https://github.com/sandros94) Typically you should not author `.d.ts` files. And if you do you should not import from them. Instead, author `.ts` files, and the `.d.ts` files are produced _from_ them.

Thank you 🙏
By any chance, and if I don't wast too much of your time, do you have any source where I can learn the reasons behind this?

**Comment by danielroe** [comment]
@sandros94 I don't have a source at the top of my mind - I suspect something like https://www.totaltypescript.com would explain the different 'contexts' within TS.
